### ISSUE TITLE
AWS KeyPair should be configurable and reusable

### ISSUE THREAD

**Issue by code4dc** [cratekube/cloud-mgmt-service#29]
### Problem to solve

The cloud-mgmt-service will attempt to create a new keypair everytime it spins up an environment instead of checking whther one already exists and reusing it. 

### Proposal

This will be resolved by having the cloud-mgmt-service use a configurable keypair name and checking if the keypair already exists and reusing it if it does. 

### Intended users

Developer

### Further details

This should resolve the following error which occurs during testing when a POST request attempts to create an environment that already exists in AWS but not in the cloud-mgmt-service (due to a restart). 
```
Error: Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'cratekube-key-pair' already exists.
        status code: 400, request id: 5f80b7f2-82ab-40d3-8298-4b5f04f7ab2b
```

### Permissions and Security

N/A

### Documentation

Add documentation regarding the ability to configure the KeyPair name

### How can we measure success?

N/A

### When is this feature complete?

KeyPair name is configurable
KeyPair is reused if it already exists in AWS

**Comment by kod4n** [comment]
I've got an update to the current terraform templates that allow for the keypair name to be configurable via a dropwizard configuration.  Setting up a PR to get a change through.
